### ISSUE TITLE
Incoming mail not working with code 500

### ISSUE THREAD

**Issue by promasu** [loomio/loomio#10163]
Hello team,

I have the problem that in my deployment the email processor is not working.
My mailin service gives me the error message:
```
error: cab83cf2-ae30-44f3-b143-2cd26212f269 Error in posting to webhook http://loomio-server:3000/email_processor/
error: cab83cf2-ae30-44f3-b143-2cd26212f269 Response status code: 500
```

The logs of the loomio app server states:

```
I, [2024-01-03T13:52:36.857803 #12]  INFO -- : [86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df] method=POST path=/email_processor format=html controller=ReceivedEmailsController action=create status=500 allocations=12069 duration=46.31 view=0.00 db=31.33
F, [2024-01-03T13:52:36.858463 #12] FATAL -- : [86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df]
[86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df] NoMethodError (undefined method `downcase' for nil:NilClass):
[86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df]
[86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df] app/services/received_email_service.rb:21:in `route'
[86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df] app/controllers/received_emails_controller.rb:10:in `create'
[86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df] app/helpers/locales_helper.rb:8:in `use_preferred_locale'
[86cb4efb-7675-48b8-ba3e-4f2fdf2ce7df] app/helpers/locales_helper.rb:3:in `process_time_zone'
```

Do you have any idea where this is coming from?

I'm running a docker setup with version loomio/loomio:v2.21.4

**Comment by robguthrie** [comment]
Line 21 of received_email_service:
```
return nil if email.sender_hostname.downcase == ENV['SMTP_DOMAIN'].downcase
```

So looks like you do not have SMTP_DOMAIN defined in your .env file.

**Comment by promasu** [comment]
Ah thanks!
I just added the SMTP_DOMAIN setting, loomio server logs:

```
I, [2024-01-04T10:46:06.845110 #11]  INFO -- : source=rack-timeout id=749f79b9-8828-47cc-b3b5-d08901dfefd5 timeout=15000ms state=ready
I, [2024-01-04T10:46:06.874326 #11]  INFO -- : [749f79b9-8828-47cc-b3b5-d08901dfefd5] method=POST path=/email_processor format=html controller=ReceivedEmailsController action=create status=200 allocations=9211 duration=27.94 view=0.00 db=13.38
I, [2024-01-04T10:46:06.874805 #11]  INFO -- : source=rack-timeout id=749f79b9-8828-47cc-b3b5-d08901dfefd5 timeout=15000ms service=30ms state=completed
```

But my mail does not appear in the thread I sent the mail to.
Any idea why I have this problem?
I send the mail from the same address as my user has.

**Comment by robguthrie** [comment]
Sorry for the delay. So emailing the group (group-handle@loomio.example.com) will always start a new thread. There is a special reply address on thread notifications so reply emails are added as comments.

Is that the answer to your question?
