### ISSUE TITLE
Custom install of Loomio doesn't show dashboard

### ISSUE THREAD

**Issue by sicarul** [loomio/loomio#2754]
Hello, i've installed Loomio with Dokku, following this guide:

https://loomio.gitbooks.io/tech-manual/content/install_loomio_with_dokku.html

A previous version of Loomio worked fine with the same method of installation, but when i updated it, it stopped working. I deleted the database and started from scratch (As it wasn't production yet) and now it doesn't work.

Authentication works fine, but when entering the dashboard all css/js assets fail to load (app.css, app.js, vendor.js), when i look at the logs i find this:

```
05:00:00 web.1    | Started GET "/js/app.js?1448427599" for 186.136.134.34 at 2015-11-25 05:00:00 +0000
05:00:00 web.1    | 
05:00:00 web.1    | ActionController::RoutingError (No route matches [GET] "/js/app.js"):
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/ahoy_matey-1.1.1/lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/heroku-deflater-0.5.3/lib/heroku-deflater/skip_binary.rb:19:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/heroku-deflater-0.5.3/lib/heroku-deflater/serve_zipped_assets.rb:50:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/configuration.rb:51:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
05:00:00 web.1    |   vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
05:00:00 web.1    | 
05:00:00 web.1    | 
```

Can you help me to get this working? Is there any other log/config file that would be useful for you to debug what's wrong? I read something about 2 ports but when installing with dokku it automatically replaces the nginx file every time i deploy with Dokku.

Thanks!

**Comment by sicarul** [comment]
I'm running this version: 3a8c316060920e6cb41f63e5cf9e8d2abe8e1ded

**Comment by gdpelican** [comment]
Hi @sicarul, sounds like you haven't gotten lineman running to enable the new angular interface yet. Have you had a look at this guide?
https://loomio.gitbooks.io/tech-manual/content/using_development.html

@robguthrie It seems like a lot of people are running into this and I'm wondering if we can give a little love / visibility to the tech manual in the near future to remove what seems to be a pretty common, pretty easy-to-remove hurdle.

**Comment by robguthrie** [comment]
yes tech-manual is prioritised in next sprint

**Comment by sicarul** [comment]
@gdpelican Thanks for answering! Though that refers to a development environment, i didn't install it on a development environment, i went directly to the production environment, do i have to install lineman on the production server?

**Comment by gdpelican** [comment]
Yep, you'll need to run lineman in production as well. :+1: 
We'll be updating the docs for this to make it a much easier path to follow over the next week or so.
