### ISSUE TITLE
Unable to display dashboard with latest loomio docker image (RoutingError)

### ISSUE THREAD

**Issue by uportalis** [loomio/loomio#3418]
I just updated my loomio-deploy install with these commands:
docker-compose down
docker-compose pull
docker-compose up -d

Now, when I log in, I get the "We're sorry, but something went wrong." page and the error below in the logs.

```
loomio_1 | Started GET "/assets/loomio-orange.png" for 172.17.0.7 at 2016-06-15 13:06:59 +0000
loomio_1 |
loomio_1 | ActionController::RoutingError (No route matches [GET] "/assets/loomio-orange.png"):
loomio_1 |   actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
loomio_1 |   railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
loomio_1 |   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
loomio_1 |   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
loomio_1 |   activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
loomio_1 |   railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
loomio_1 |   ahoy_matey (1.1.1) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   heroku-deflater (0.5.3) lib/heroku-deflater/skip_binary.rb:19:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   rack (1.6.4) lib/rack/deflater.rb:35:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   heroku-deflater (0.5.3) lib/heroku-deflater/serve_zipped_assets.rb:50:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   actionpack (4.2.5.2) lib/action_dispatch/middleware/ssl.rb:24:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
loomio_1 |   airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
loomio_1 |   railties (4.2.5.2) lib/rails/application.rb:165:in `call'
loomio_1 |   railties (4.2.5.2) lib/rails/railtie.rb:194:in `public_send'
loomio_1 |   railties (4.2.5.2) lib/rails/railtie.rb:194:in `method_missing'
loomio_1 |   newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
loomio_1 |   puma (2.15.3) lib/puma/configuration.rb:79:in `call'
loomio_1 |   puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
loomio_1 |   puma (2.15.3) lib/puma/server.rb:388:in `process_client'
loomio_1 |   puma (2.15.3) lib/puma/server.rb:270:in `block in run'
loomio_1 |   puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

Here is my docker image:
```
~/loomio-deploy$ docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
loomio/loomio                            latest              750a0daa49bd        3 hours ago         1.69 GB
```

**Comment by gdpelican** [comment]
Hm, that stack trace doesn't look promising, but it doesn't include the actual cause of the 500 error you're experiencing (that is a 404 Not Found for an image, which is bad, but shouldn't blow things up with a 'something went wrong' message) Would you be able to provide a complete stack trace? (should be something to the effect of `Completed 500 Internal Server Error in 7ms`

**Comment by uportalis** [comment]
Please find the full logs (docker-compose logs) in the attached file.
My scenario is to just log into the application.

[loomio.log.txt](https://github.com/loomio/loomio/files/317761/loomio.log.txt)

**Comment by gdpelican** [comment]
It looks like you're missing a migration somehow; that `Group::Counter` error says your database is out of sync. Would you be able to run `rake db:migrate` or `rake db:schema:load` on your instance to see if that runs the missing migration? (NB that the last command will wipe any existing data in your database.)

**Comment by uportalis** [comment]
I just ran `docker-compose run loomio rake db:migrate` and it works now.
Thank you.
