### ISSUE TITLE
angular gulp compile error => marked.js file not found

### ISSUE THREAD

**Issue by SachaSchlegel** [loomio/loomio#3938]
hi. i just successfully installed loomio on a linux server.

i found a problem when compiling stuff (during installation procedure) in the angular directory. 

as mentioned i did this:

npm install # creates nodes_modules directory and installs lots of packages into there
gulp compile # does stuff BUT with an error message (see below)

Seems that a package has a new name/path:
Change in file: loomio/angular/tasks/config/vendor.yml ([link to file](https://github.com/loomio/loomio/blob/master/angular/tasks/config/vendor.yml))

FROM:  - angular-marked/node_modules/marked/lib/marked.js
TO:       - marked/marked.min.js

Not sure if this is correct, but fixed the problem for me.

----------- error --------------------------
sacha@findeco:~/liquiddemocracy/loomio/loomio/angular$ gulp compile
[00:02:18] Requiring external module coffee-script/register
[00:02:22] Using gulpfile ~/liquiddemocracy/loomio/loomio/angular/gulpfile.coffee
[00:02:22] Starting 'fonts'...
[00:02:22] Starting 'app'...
[00:02:22] Starting 'vendor'...
[00:02:22] Starting 'scss'...
[00:02:22] Starting 'execjs'...
[00:02:22] Tested 3 tests, 3 passes, 0 failures: PASS
[00:02:24] Finished 'execjs' after 2.49 s
[00:02:24] Finished 'fonts' after 2.7 s
[00:02:25] ✗ FAIL: Missing 1 expected files: node_modules/angular-marked/node_modules/marked/lib/marked.js
[00:02:25] Tested 35 tests, 34 passes, 1 failures: FAIL

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error in plugin 'gulp-expect-file'
Failed 1 expectations
  at DestroyableTransform.endStream [as _flush] (/home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/gulp-expect-file/index.js:90:26)
  at DestroyableTransform.<anonymous> (/home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
  at DestroyableTransform.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:166:7)
  at prefinish (/home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:450:12)
  at finishMaybe (/home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:458:7)
  at endWritable (/home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:469:3)
  at DestroyableTransform.Writable.end (/home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/gulp-expect-file/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:436:5)
  at DestroyableTransform.onend (/home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
  at DestroyableTransform.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at DestroyableTransform.emit (events.js:166:7)
  at /home/sacha/liquiddemocracy/loomio/loomio/angular/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at nextTickCallbackWith0Args (node.js:419:9)
  at process._tickCallback (node.js:348:13)

**Comment by fauno** [comment]
you need nodejs 4 :)

-- 
P)

**Comment by gdpelican** [comment]
Yes, 4.2.6 to be precise. I've been wanting to bump up to node 5/6/etc for a while now, but have not found time to prioritize it. A PR here is most welcome.

**Comment by drskullster** [comment]
Isn't that a problem with npm ? Since v3 npm 'flattens' node_modules directories.

`angular-marked/node_modules/marked/lib/marked.js` would be met by npm v2.
`marked/lib/marked.js` would be met by npm v3.

I can write a PR (though I'm not familiar with coffeescript) but I don't see exactly how we could resolve this issue. Maybe check npm version in gulp ? Or add a fallback path for some files in case of failure ?

**Comment by gdpelican** [comment]
We've just, in the past couple days, updated our packages to use node 7.4 / npm 4.0.5, so I think it'll be safe to assume going forward that a modern version of node / npm will work.

**Comment by GenericUK** [comment]
@gdpelican I'm writing a development install article for Ubuntu 16.04. I've just come across this issue with `Missing 1 expected files: node_modules/marked/lib/marked.js` I got round it by installing `npm install marked` it appears that Gulp compile config doesn't find angular-marked. 

From your last comment, does this mean Loomio development should officially now use node 7.4. quickstart.md says Node 4.2.6 and setup_environment.md says 4.4.5. It would be great if someone could clarify which version of Node and NPM is current and if this could be kept up to date in the master readme.

**Comment by awoo100-zh** [comment]
I'm wondering if this issue is related to one I'm getting.

I had the same issue, however over 25 files were not found, including Marked. I am using version 8.2.1. I've managed to manually install 23 of the files, but have two remaining and can't work out how to get them through npm. The two "Expected Files" are node_modules/loomio-angular-router/dist/router.es5,js and node_modules/loomio-angular-marked/dist/angular-marked.js

I will admit I've had some issues with the install due to being inside the great firewall, so it could be that I missed a package...

**Comment by gdpelican** [comment]
Hi @awoo100-zh ,

I'm not too familiar with getting around the firewall to npm, but running `yarn` or `npm install` on a VPN connection (or maybe through Tor?) would probably be your best bet there.

I'd discourage installing manually except as a last resort; we update those packages fairly regularly and as you've seen, we don't run the app unless we can detect each of the dependencies on your machine.

The direct links to those packages (which are our own internal forks of other open source repos) are here:
https://www.npmjs.com/package/loomio-angular-router
https://www.npmjs.com/package/loomio-angular-marked

**Comment by awoo100-zh** [comment]
Thanks for your prompt response @gdpelican 

I tried these npm install packages commands, but the files were being stored in the "angular-new-router" directory, rather than the "loomio-angular-router" directory. I manually renamed the directory just to get it to compile. But this is a hacky work around, and not sure if this will have implications further down the line.

**Comment by kittkatter** [comment]
```
build list:

[modules] base v0.2.11 (ignoring)
[modules] console v0.1.11 (ignoring)
[modules] monitor v0.2.4 (ignoring)
[modules] portmaster v0.1.13 

press [Enter] to start building

base is being ignored, skipping...
console is being ignored, skipping...
monitor is being ignored, skipping...

packaging portmaster


> portmaster@0.1.13 build /home/user/test/portmaster-ui/modules/portmaster
> NODE_ENV=production ng build --prod --base-href /ui/modules/portmaster/ --deploy-url /ui/modules/portmaster/

Option "--prod" is deprecated: Use "--configuration production" instead.
Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: Script file node_modules/marked/lib/marked.js does not exist.
See "/tmp/ng-vLa64I/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! portmaster@0.1.13 build: `NODE_ENV=production ng build --prod --base-href /ui/modules/portmaster/ --deploy-url /ui/modules/portmaster/`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the portmaster@0.1.13 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-08-19T07_46_54_939Z-debug.log

[modules] portmaster v0.1.13: BUILD FAILED.

```

**Comment by kokizzu** [comment]
I fix this by adding:
```
(cd node_modules/marked/lib && ln -sf marked.esm.js marked.js) &&
```
before whatever command need to run
