### ISSUE TITLE
uninitialized constant Group::Counter

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3971]
i'm getting this with latest commits (at least since b48887f088fc8673598ba46e904acd0c70bf8a8f afaict)

```ruby
NameError (uninitialized constant Group::Counter):
  app/models/current_user_data.rb:3:in `data'
  app/helpers/angular_helper.rb:27:in `app_config'
  app/helpers/angular_helper.rb:6:in `boot_angular_ui'
  app/helpers/uses_metadata.rb:9:in `show'
  app/controllers/application_controller.rb:83:in `user_time_zone'
```

**Comment by fauno** [comment]
this went away when i migrated the polls
