### ISSUE TITLE
email_community in PollSerializer?

### ISSUE THREAD

**Issue by fauno** [loomio/loomio#3989]
I'm getting this stack when visiting a discussion thread:

```ruby
App 14342 stdout: Started GET "/api/v1/polls?discussion_id=2bUEQm1G" for 127.0.0.1 at 2017-03-22 11:26:44 -0400
App 14342 stdout: Processing by API::PollsController#index as JSON
App 14342 stdout:   Parameters: {"discussion_id"=>"2bUEQm1G"}
App 14342 stdout: Completed 500 Internal Server Error in 28ms (ActiveRecord: 4.2ms)
App 14342 stdout:
App 14342 stdout: NoMethodError (undefined method `id' for nil:NilClass):
App 14342 stdout:   app/serializers/poll_serializer.rb:20:in `email_community_id'
App 14342 stdout:   app/controllers/api/restful_controller.rb:48:in `respond_with_collection'
App 14342 stdout:   app/controllers/api/polls_controller.rb:15:in `index'
App 14342 stdout:
App 14342 stdout:
App 14342 stdout: Started GET "/api/v1/stances/my_stances?discussion_id=2bUEQm1G" for 127.0.0.1 at 2017-03-22 11:26:44 -0400
App 14342 stdout: Processing by API::StancesController#my_stances as JSON
App 14342 stdout:   Parameters: {"discussion_id"=>"2bUEQm1G"}
App 14342 stdout: Completed 500 Internal Server Error in 30ms (ActiveRecord: 3.5ms)
App 14342 stdout:
App 14342 stdout: NoMethodError (undefined method `id' for nil:NilClass):
App 14342 stdout:   app/serializers/poll_serializer.rb:20:in `email_community_id'
App 14342 stdout:   app/controllers/api/restful_controller.rb:48:in `respond_with_collection'
App 14342 stdout:   app/controllers/api/stances_controller.rb:8:in `my_stances'
```

what's a community?  how do it create the missing email communities?

**Comment by robguthrie** [comment]
@gdpelican did you see this? (Have you settled on a robust way to address this?)

**Comment by gdpelican** [comment]
Puzzling about it now. We have a similar robustness problem around email identities as well, so it's an arch question we'll want a good answer to.

We fixed this in prod by running
```
Poll.all.each { |p| p.community_of_type(:email, build: true); p.save }
```
