### ISSUE TITLE
Historical proposals and outcomes lost in upgrade

### ISSUE THREAD

**Issue by tanc** [loomio/loomio#4259]
We hadn't upgraded Loomio in about a year and I managed to successfully run the rake db:migrate task to upgrade the database. Everything ran fine but when logging in now I can't see the results of previous proposals or even what they were. Should there be a migration path for proposals? Have I missed something?

**Comment by robguthrie** [comment]
Hi @tanc I'm really sorry this happened to you!

Do you have a backup of your database? I'm afraid that your data is lost if do you don't. 

The migration from Motions to multiple poll types happened a couple of months ago, and more recently we removed all the old code from the system.

I'm working on a fix for this so that data is migrated automatically.

Again, I'm really sorry this happened and I'm hoping that you've not lost important data.

**Comment by robguthrie** [comment]
Hello @tanc,

I've just committed a fix for this. I'm really sorry you had this problem. If you were to migrate your database from today, the conversion to polls will happen automatically.

**Comment by tanc** [comment]
Hi @robguthrie I do have a backup. So the steps would be:

1. Revert to backup of the database
2. Pull the latest Docker image
3. Re-run the db migrations

I'll give that a try and report back.

**Comment by robguthrie** [comment]
oh thank goodness you have a backup! *sigh of relief*

That's right re: steps.

**Comment by tanc** [comment]
Just struggling with importing the database. Do you have a handy one-liner to import?

**Comment by robguthrie** [comment]
Yes!

Backup and restore SQL file
pg_dump -c loomio_development -f filename.sql
psql -U rob -d loomio_development -f filename.sql

drop and create:
dropdb loomio_development
createdb loomio_development

restore dump:
pg_restore --verbose --clean --no-acl --no-owner -d loomio_development
~/loomio_development.dump

**Comment by tanc** [comment]
Thanks for that!

Now running `rake db:migrate` I get the following error:

```
Migrating to DropMotionsAndVotes (20170705095538)
rake aborted!
NoMethodError: undefined method `belongs_to' for Poll:Class
/loomio/db/migrate/legacy/models/poll.rb:2:in `<class:Poll>'
/loomio/db/migrate/legacy/models/poll.rb:1:in `<top (required)>'
/loomio/db/migrate/legacy/convert_motions_to_polls.rb:4:in `require_relative'
/loomio/db/migrate/legacy/convert_motions_to_polls.rb:4:in `<top (required)>'
/loomio/db/migrate/20170705095538_drop_motions_and_votes.rb:1:in `require_relative'
/loomio/db/migrate/20170705095538_drop_motions_and_votes.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:777:in `load_migration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:773:in `migration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1051:in `use_transaction?'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:958:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
NoMethodError: undefined method `belongs_to' for Poll:Class
/loomio/db/migrate/legacy/models/poll.rb:2:in `<class:Poll>'
/loomio/db/migrate/legacy/models/poll.rb:1:in `<top (required)>'
/loomio/db/migrate/legacy/convert_motions_to_polls.rb:4:in `require_relative'
/loomio/db/migrate/legacy/convert_motions_to_polls.rb:4:in `<top (required)>'
/loomio/db/migrate/20170705095538_drop_motions_and_votes.rb:1:in `require_relative'
/loomio/db/migrate/20170705095538_drop_motions_and_votes.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:777:in `load_migration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:773:in `migration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1051:in `use_transaction?'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
```

**Comment by tanc** [comment]
I tried modifying the migration `/loomio/db/migrate/20170705095538_drop_motions_and_votes.rb` so that it reads:

```
class Poll < ActiveRecord::Base
  belongs_to :motion
end
```

This allows the migration to begin but it immediately fails with:
```
Migrating to DropMotionsAndVotes (20170705095538)
== 20170705095538 DropMotionsAndVotes: migrating ==============================
converting 103 motions to polls
1
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown attribute 'poll_options_attributes' for Poll.
```

**Comment by robguthrie** [comment]
That's odd. On my system app/models/poll.rb is loaded before this. So the class Poll extends the existing class.

If you run `bundle exe rake db:migrate` does it load differently?

**Comment by tanc** [comment]
I get the same error:

```
$ bundle exec rake db:migrate
/usr/local/bundle/gems/rb-readline-0.5.3/lib/readline.rb:458: warning: already initialized constant Readline::HISTORY
/usr/local/bundle/gems/rb-readline-0.5.3/lib/readline.rb:486: warning: already initialized constant Readline::FILENAME_COMPLETION_PROC
/usr/local/bundle/gems/rb-readline-0.5.3/lib/readline.rb:517: warning: already initialized constant Readline::USERNAME_COMPLETION_PROC
/usr/local/bundle/gems/rb-readline-0.5.3/lib/readline.rb:523: warning: already initialized constant Readline::VERSION
Migrating to DropMotionsAndVotes (20170705095538)
rake aborted!
NoMethodError: undefined method `belongs_to' for Poll:Class
/loomio/db/migrate/legacy/models/poll.rb:2:in `<class:Poll>'
/loomio/db/migrate/legacy/models/poll.rb:1:in `<top (required)>'
/loomio/db/migrate/legacy/convert_motions_to_polls.rb:4:in `require_relative'
/loomio/db/migrate/legacy/convert_motions_to_polls.rb:4:in `<top (required)>'
/loomio/db/migrate/20170705095538_drop_motions_and_votes.rb:1:in `require_relative'
/loomio/db/migrate/20170705095538_drop_motions_and_votes.rb:1:in `<top (required)>'
```

**Comment by tanc** [comment]
@robguthrie do you have any advice of what else I could try?

**Comment by tanc** [comment]
Brilliant! That worked 👍 

I then edited /loomio/db/migrate/20170705095538_drop_motions_and_votes.rb and removed the include and convert_motions_to_polls call and the rest of the migrations have run successfully now.

Logging into the updated site I can see that our old motions/decisions have been converted to polls and preserved. Happy days! Thanks so much for you help :)
