### ISSUE TITLE
Build by Migrations fail

### ISSUE THREAD

**Issue by joshco** [loomio/loomio#4280]
When attempting to set up the application by using rake db:migrate (rather than schema.rb load) multiple migrations fail with

> NameError: uninitialized constant CreateDidNotVotesForMotions::Motion
> /vagrant/loomio/lib/plugins/module_const_missing.rb:4:in `const_missing'
> /vagrant/loomio/db/migrate/20120501031029_create_did_not_votes_for_motions.rb:3:in `up'

Looks like the legacy models in the db directory are not loading for rake
I'm running on ubuntu.

**Comment by robguthrie** [comment]
Hi Josh, you can get around that by running `rake db:setup` instead.

Happy to fix that soon though

**Comment by joshco** [comment]
That's what I'm doing now.  I originally tried the migrations b/c i need to just use json (not jsonb) with postgres right now.  Though it's ended up easier to just modify schema.rb, which is what I just did.
thx

**Comment by joshco** [comment]
ok that got the database solved.  now stuck on gulp/coffee problems

````
vagrant@joshco:/vagrant/loomio/angular$ gulp compile
[03:01:37] Failed to load external module coffee-script/register
[03:01:37] Failed to load external module coffee-script
[03:01:37] Failed to load external module coffeescript/register
[03:01:37] Failed to load external module coffeescript
/vagrant/loomio/angular/gulpfile.coffee:1
(function (exports, require, module, __filename, __dirname) { gulp     = require 'gulp'
                                                                                 ^^^^^^
SyntaxError: Unexpected string
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/home/vagrant/.nvm/versions/node/v7.4.0/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/vagrant/.nvm/versions/node/v7.4.0/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
````

and

````
vagrant@joshco:/vagrant/loomio/angular$ coffee
module.js:472
    throw err;
    ^

Error: Cannot find module '/vagrant/loomio/angular/node_modules/coffee-script/lib/coffee-script/command'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v7.4.0/lib/node_modules/coffeescript/bin/coffee:15:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
````

but I've done npm install -g coffee and it didn't complain.

**Comment by robguthrie** [comment]
did you run `yarn` to install dependencies?

**Comment by joshco** [comment]
yarn did it, thanks!  I had to run it with --no-bin-links since I'm running in vagrant.  Some of the packages symlink their binaries.  However with vagrant and virtualbox shared filesystems, symlinks are not supported.
