### ISSUE TITLE
Assigning admin status through Active Admin broken

### ISSUE THREAD

**Issue by aerugo** [loomio/loomio#4570]
It seems that I can't assign admin status through the Active Admin interface. Looks like there is some new field check on users. I'm currently following the master branch, updated a couple of days ago, but not sure how long this has been a problem, I haven't tried using this for a while. Here are the logs.

```
loomio_1       | Started PATCH "/admin/users/VAGUtS1C" for 193.11.192.160 at 2018-03-07 15:38:12 +0000
loomio_1       | Processing by Admin::UsersController#update as HTML
loomio_1       |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"TOKEN", "user"=>{"name"=>"Some Name", "email"=>"somename@gmail.com", "username"=>"somename", "is_admin"=>"1"}, "commit"=>"Update User", "id"=>"ID"}
db_1           | ERROR:  null value in column "angular_ui_enabled" violates not-null constraint
db_1           | DETAIL:  Failing row contains (15, somename@gmail.com, , null, null, 2018-01-06 15:32:16.094895, 25, 2018-03-07 15:20:25.683944, 2018-02-22 18:02:19.964475, 89.160.27.18, 51.179.112.204, 2018-01-06 15:32:15.936755, 2018-03-07 15:38:12.274582, Jakob Sköte, null, t, uploaded, 17362922_10154410666372045_3463722106149679756_n.jpg, image/jpeg, 4666, 2018-01-06 15:32:16.510046, JS, jakobskote, f, null, ID, 10, f, null, Europe/Copenhagen, VAGUtS1C, en_GB, f, ed03e1f2f1f4ac0b489b04cf579e4cc8, t, null, f, 2, Norway, null, null, {"dismissThread": true, "proposal_tool_tip": true}, null, null, ID, , t, , 2018-03-07 15:27:23.20481).
db_1           | STATEMENT:  UPDATE "users" SET "is_admin" = $1, "angular_ui_enabled" = $2, "updated_at" = $3 WHERE "users"."id" = $4
loomio_1       | Completed 401 Unauthorized in 14ms (ActiveRecord: 4.8ms)
loomio_1       |   
loomio_1       | ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "angular_ui_enabled" violates not-null constraint
loomio_1       | DETAIL:  Failing row contains (15, somename@gmail.com, , null, null, 2018-01-06 15:32:16.094895, 25, 2018-03-07 15:20:25.683944, 2018-02-22 18:02:19.964475, 89.160.27.18, 51.179.112.204, 2018-01-06 15:32:15.936755, 2018-03-07 15:38:12.274582, Jakob Sköte, null, t, uploaded, 17362922_10154410666372045_3463722106149679756_n.jpg, image/jpeg, 4666, 2018-01-06 15:32:16.510046, JS, jakobskote, f, null, ID, 10, f, null, Europe/Copenhagen, VAGUtS1C, en_GB, f, ed03e1f2f1f4ac0b489b04cf579e4cc8, t, null, f, 2, Norway, null, null, {"dismissThread": true, "proposal_tool_tip": true}, null, null, ID, , t, , 2018-03-07 15:27:23.20481).
loomio_1       | : UPDATE "users" SET "is_admin" = $1, "angular_ui_enabled" = $2, "updated_at" = $3 WHERE "users"."id" = $4):
loomio_1       |   
loomio_1       | app/admin/users.rb:83:in `block (2 levels) in <top (required)>'
loomio_1       | app/helpers/locales_helper.rb:4:in `use_preferred_locale'
loomio_1       | app/controllers/application_controller.rb:41:in `process_time_zone'
nginx_1        | nginx.1    | talk.theborderland.se 193.11.192.160 - - [07/Mar/2018:15:38:12 +0000] "POST /admin/users/VAGUtS1C HTTP/2.0" 500 398 "https://talk.theborderland.se/admin/users/VAGUtS1C/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"
loomio_1       | Started GET "/favicon.ico" for 193.11.192.160 at 2018-03-07 15:38:12 +0000
loomio_1       | Processing by ApplicationController#ok as HTML
loomio_1       | Completed 200 OK in 7ms (ActiveRecord: 2.1ms)
nginx_1        | nginx.1    | talk.theborderland.se 193.11.192.160 - - [07/Mar/2018:15:38:12 +0000] "GET /favicon.ico HTTP/2.0" 200 25 "https://talk.theborderland.se/admin/users/VAGUtS1C" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36"
```

**Comment by gdpelican** [comment]
I'm able to do this on Loomio.org, so I don't believe this is a problem with the current app.

Have you run rake db:migrate on your instance recently? angular_ui_enabled should be dropped from the schema in latest.

**Comment by gdpelican** [comment]
Were you able to resolve this by migrating the db @aerugo ?

**Comment by aerugo** [comment]
I'm back to tracking the stable branch, and it works now. Migrating didn't solve it while I was on master for some reason.
