### ISSUE TITLE
rake bootstrap error: BCrypt::Errors::InvalidHash: invalid hash

### ISSUE THREAD

**Issue by lezardbreton** [loomio/loomio#4756]
After following the instructions to install on my machine (Fedora, using latest rvm, ruby and gems), I have the folllowing error message post table creations:
```
-- create_table("webhooks", {:id=>:serial, :force=>:cascade})
   -> 0.0212s
rake aborted!
BCrypt::Errors::InvalidHash: invalid hash
/home/user/.rvm/gems/ruby-2.5.1/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:60:in `initialize'
/home/user/.rvm/gems/ruby-2.5.1/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:46:in `new'
/home/user/.rvm/gems/ruby-2.5.1/gems/bcrypt-3.1.11/lib/bcrypt/password.rb:46:in `create'
/home/user/.rvm/gems/ruby-2.5.1/gems/devise-4.4.3/lib/devise/encryptor.rb:11:in `digest'
/home/user/.rvm/gems/ruby-2.5.1/gems/devise-4.4.3/lib/devise/models/database_authenticatable.rb:167:in `password_digest'
/home/user/.rvm/gems/ruby-2.5.1/gems/devise-4.4.3/lib/devise/models/database_authenticatable.rb:47:in `password='
/home/user/.rvm/gems/ruby-2.5.1/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:46:in `public_send'
/home/user/.rvm/gems/ruby-2.5.1/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:46:in `_assign_attribute'
/home/user/.rvm/gems/ruby-2.5.1/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/home/user/.rvm/gems/ruby-2.5.1/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:39:in `each'
/home/user/.rvm/gems/ruby-2.5.1/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/home/user/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.6/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/home/user/.rvm/gems/ruby-2.5.1/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/home/user/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.6/lib/active_record/core.rb:337:in `initialize'
/home/user/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.6/lib/active_record/inheritance.rb:66:in `new'
/home/user/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.6/lib/active_record/inheritance.rb:66:in `new'
/home/user/.rvm/gems/ruby-2.5.1/gems/activerecord-5.1.6/lib/active_record/persistence.rb:33:in `create'
/home/user/Development/loomio/lib/tasks/bootstrap.rake:31:in `block (2 levels) in <top (required)>'
/home/user/Development/loomio/lib/tasks/bootstrap.rake:78:in `block in <top (required)>'
/home/user/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => bootstrap:create_user
```

Any step I've missed? I have not yet tried to debug.

**Comment by robguthrie** [comment]
we dont have a bootstrap task anymore. closing.
