### ISSUE TITLE
Migration dependency missing

### ISSUE THREAD

**Issue by asdofindia** [loomio/loomio#8574]
[The migration at 20200916234818_update_attachments_group_id.rb](https://github.com/loomio/loomio/blob/master/db/migrate/20200916234818_update_attachments_group_id.rb)

```
class UpdateAttachmentsGroupId < ActiveRecord::Migration[5.2]
  def change
    return if ENV['CANONICAL_HOST'] == 'www.loomio.org'
    ActiveStorage::Attachment.where(group_id: nil).where(record_type: ['Discussion', 'Comment', 'Poll']).find_each do |a|
      next unless a && a.record
      UpdateAttachmentsGroupIdWorker.perform_async(a.record.class.to_s, a.record.id)
    end
  end
end
```

depends on 

UpdateAttachmentsGroupIdWorker which was removed in #7152

[History of that file](https://github.com/loomio/loomio/commits/master/app/workers/update_attachments_group_id_worker.rb)

This breaks migrations from very old versions with this error:

```

Migrating to UpdateAttachmentsGroupId (20200916234818)
== 20200916234818 UpdateAttachmentsGroupId: migrating =========================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant UpdateAttachmentsGroupId::UpdateAttachmentsGroupIdWorker
/loomio/lib/plugins/module_const_missing.rb:4:in `const_missing'
/loomio/db/migrate/20200916234818_update_attachments_group_id.rb:6:in `block in change'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:71:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:71:in `each'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:71:in `block in find_each'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:229:in `loop'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:70:in `find_each'
/loomio/db/migrate/20200916234818_update_attachments_group_id.rb:4:in `change'
...
```

Is it safe to skip this migration?

**Comment by robguthrie** [comment]
yep, safe to skip it.

if need be you can fix that issue later, but I don't think you will need to.

More recently I've been using better versioning, and you should get an error specifying which version you need to drop down to before continuing

**Comment by asdofindia** [comment]
I could prevent this by [going through v2.4.2](https://status.fsci.in/issues/20220516-codema.in-update/)

**Comment by robguthrie** [comment]
I've updated the readme for loomio/loomio-deploy with a note on this. Hopefully we grow this section of the readme.
