### ISSUE TITLE
MigratePaperclipAttachments crashes because of missing "templates" relation

### ISSUE THREAD

**Issue by asdofindia** [loomio/loomio#8576]
```
Migrating to MigratePaperclipAttachments (20210826234109)
== 20210826234109 MigratePaperclipAttachments: migrating ======================
#<Group:0x00005621c696cad8>
#<Group:0x00005621c5cde848>
#<Group:0x00005621c5cde3c0>
#<Group:0x00005621c5cdddf8>
#<Group:0x00005621c5cdd880>
#<Group:0x00005621c5cdd2e0>
#<Group:0x00005621c5cdcc28>
#<Group:0x00005621c5cdc688>
#<Group:0x00005621c5cdc070>
#<Group:0x00005621c735fb58>
#<Group:0x00005621c735f6f8>
#<Group:0x00005621c735f2c0>
#<Group:0x00005621c735ee88>
#<Group:0x00005621c735ea28>
#<Group:0x00005621c735e578>
#<Group:0x00005621c735e118>
#<Group:0x00005621c735dcb8>
#<Group:0x00005621c735d858>
#<Group:0x00005621c735d420>
#<Group:0x00005621c735cfe8>
#<Group:0x00005621c735cbb0>
#<Group:0x00005621c735c778>
#<Group:0x00005621c735c340>
#<Group:0x00005621c5ccfdc0>
#<Group:0x00005621c5ccf960>
#<Group:0x00005621c5ccf4d8>
#<Group:0x00005621c5ccef10>
#<Group:0x00005621c5ccea38>
#<Group:0x00005621c5cce4e8>
#<Group:0x00005621c5ccdfc0>
#<Group:0x00005621c5ccda70>
#<Group:0x00005621c5ccd570>
#<Group:0x00005621c5ccd070>
#<Group:0x00005621c5cccad0>
#<Group:0x00005621c5ccc490>
#<Group:0x00005621c0e53f98>
#<Group:0x00005621c0e53b60>
#<Group:0x00005621c0e53700>
#<Group:0x00005621c0e532c8>
#<Group:0x00005621c0e52e90>
#<Group:0x00005621c0e52a58>
#<Group:0x00005621c0e52620>
#<Group:0x00005621c0e521e8>
#<Group:0x00005621c0e51db0>
#<Group:0x00005621c0e51950>
#<Group:0x00005621c0e51518>
#<Group:0x00005621c0e510e0>
#<Group:0x00005621c0e50ca8>
#<Group:0x00005621c0e50870>
#<Group:0x00005621c0e50438>
#<FormalGroup:0x00005621c56efbd0>
#<FormalGroup:0x00005621c0f3f100>
#<FormalGroup:0x00005621c0f3eca0>
#<FormalGroup:0x00005621c0f3e840>
#<FormalGroup:0x00005621c0f3e3e0>
#<FormalGroup:0x00005621c0f3df80>
#<FormalGroup:0x00005621c0f3db20>
#<FormalGroup:0x00005621c0f3d6c0>
#<FormalGroup:0x00005621c0f3d210>
#<FormalGroup:0x00005621c0f3cd60>
#<FormalGroup:0x00005621c0f3c900>
#<FormalGroup:0x00005621c0f3c4c8>
#<FormalGroup:0x00005621c0f3c090>
#<FormalGroup:0x00005621c4dabba0>
#<FormalGroup:0x00005621c4dab2e0>
#<FormalGroup:0x00005621c4daadb8>
#<FormalGroup:0x00005621c4daa958>
#<FormalGroup:0x00005621c4daa3e0>
#<FormalGroup:0x00005621c4da9f30>
#<FormalGroup:0x00005621c4da9918>
#<FormalGroup:0x00005621c4da9468>
#<FormalGroup:0x00005621c4da9008>
#<FormalGroup:0x00005621c4da8ae0>
#<FormalGroup:0x00005621c4da8428>
#<FormalGroup:0x00005621c4da9d78>
#<FormalGroup:0x00005621c53c7728>
#<FormalGroup:0x00005621c53c71d8>
#<FormalGroup:0x00005621c53c6d28>
#<FormalGroup:0x00005621c53c68a0>
#<FormalGroup:0x00005621c53c63c8>
#<FormalGroup:0x00005621c53c5e28>
#<FormalGroup:0x00005621c53c5950>
#<FormalGroup:0x00005621c53c5450>
#<FormalGroup:0x00005621c53c4f00>
#<FormalGroup:0x00005621c53c4ac8>
#<FormalGroup:0x00005621c53c4668>
#<FormalGroup:0x00005621c53c4230>
#<FormalGroup:0x00005621c4e83d48>
#<FormalGroup:0x00005621c4e83898>
#<FormalGroup:0x00005621c4e833e8>
#<FormalGroup:0x00005621c4e82d58>
#<FormalGroup:0x00005621c4e826c8>
#<FormalGroup:0x00005621c4e82218>
#<FormalGroup:0x00005621c4e81d90>
#<FormalGroup:0x00005621c4e81868>
#<FormalGroup:0x00005621c4e81408>
#<FormalGroup:0x00005621c4e80f80>
#<FormalGroup:0x00005621c4e80b48>
#<FormalGroup:0x00005621c4e80558>
#<FormalGroup:0x00005621c4e800f8>
#<GuestGroup:0x00005621c54fb630>
#<GuestGroup:0x00005621c4ddc188>
#<GuestGroup:0x00005621c4dc74b8>
#<GuestGroup:0x00005621c4dc6860>
#<GuestGroup:0x00005621c4dc6130>
#<GuestGroup:0x00005621c4dc5a78>
#<GuestGroup:0x00005621c4dc51e0>
#<GuestGroup:0x00005621c4dc46c8>
#<GuestGroup:0x00005621c4dc3908>
#<GuestGroup:0x00005621c4dc1c20>
#<GuestGroup:0x00005621c4da7b90>
#<GuestGroup:0x00005621c4da68d0>
#<GuestGroup:0x00005621c4da5f48>
#<GuestGroup:0x00005621c4da5548>
#<GuestGroup:0x00005621c4da4b20>
#<GuestGroup:0x00005621c4da4008>
#<GuestGroup:0x00005621c4da3130>
#<GuestGroup:0x00005621c4da16a0>
#<GuestGroup:0x00005621c4da0188>
#<GuestGroup:0x00005621c4d8b7b0>
#<GuestGroup:0x00005621c4d8ace8>
#<GuestGroup:0x00005621c4d8a298>
#<GuestGroup:0x00005621c4d89640>
#<GuestGroup:0x00005621c4d88c90>
#<GuestGroup:0x00005621c4d88380>
#<GuestGroup:0x00005621c4d86c60>
#<GuestGroup:0x00005621c4d85c48>
#<GuestGroup:0x00005621c4d844b0>
#<GuestGroup:0x00005621c4d837b8>
#<GuestGroup:0x00005621c4d82e30>
#<GuestGroup:0x00005621c4d81c10>
#<GuestGroup:0x00005621c4d81148>
#<GuestGroup:0x00005621c4d6f790>
#<GuestGroup:0x00005621c4d6e980>
#<GuestGroup:0x00005621c4d6de90>
#<GuestGroup:0x00005621c4d6d328>
#<GuestGroup:0x00005621c4d6c540>
#<GuestGroup:0x00005621c4d63b20>
#<GuestGroup:0x00005621c4d62d60>
#<GuestGroup:0x00005621c4d619d8>
#<GuestGroup:0x00005621c4d60650>
#<GuestGroup:0x00005621c4d43bb8>
#<GuestGroup:0x00005621c4d431e0>
#<GuestGroup:0x00005621c4d42c40>
#<GuestGroup:0x00005621c4d423d0>
#<GuestGroup:0x00005621c4d41e30>
#<GuestGroup:0x00005621c4d41728>
#<GuestGroup:0x00005621c4d40670>
#<GuestGroup:0x00005621c4d3bf80>
#<GuestGroup:0x00005621c4d3b968>
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "templates" does not exist
LINE 8:  WHERE a.attrelid = '"templates"'::regclass
                            ^
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/schema_cache.rb:111:in `fetch'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/schema_cache.rb:111:in `columns'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/schema_cache.rb:120:in `block in columns_hash'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/schema_cache.rb:119:in `fetch'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/connection_adapters/schema_cache.rb:119:in `columns_hash'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:553:in `load_schema!'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/attributes.rb:250:in `load_schema!'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:539:in `block in load_schema'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:536:in `synchronize'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:536:in `load_schema'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:397:in `columns'
/usr/local/bundle/gems/activerecord-6.1.4.4/lib/active_record/model_schema.rb:466:in `column_names'
/loomio/db/migrate/20210826234109_migrate_paperclip_attachments.rb:7:in `block in up'
/loomio/db/migrate/20210826234109_migrate_paperclip_attachments.rb:6:in `each'
/loomio/db/migrate/20210826234109_migrate_paperclip_attachments.rb:6:in `up'
```

I tried avoiding it by running the CreateTemplates migration manually:

```
docker-compose run app rake db:migrate:up VERSION=20210910045651
```

After that I could run

```
docker-compose run app rake db:migrate
```

and it ran fine (till at least) AddHideResultsToPolls (20211126003954)

**Comment by robguthrie** [comment]
Thanks for posting this. So great so see how you're finding solutions and posting them here.

**Comment by asdofindia** [comment]
For that matter, I could prevent this on production by [going through v2.8.8](https://status.fsci.in/issues/20220516-codema.in-update/)

**Comment by robguthrie** [comment]
Thank you.
