### ISSUE TITLE
Instance broken after failed update to docker latest 

### ISSUE THREAD

**Issue by airblag** [loomio/loomio#9685]
My loomio instance is running on the latest tag from docker hub.

I lastly tried to update with the `loomio-deploy/scripts/update`

It failed during the rake db:migrate step.
Rerunning it still fails with the following error : 

```
Creating loomio-db    ... done                                                                                                        
Creating loomio-redis ... done                                                                                                        
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError                             
/usr/local/bundle/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here           
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE                         
/usr/local/bundle/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here                   
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket                          
/usr/local/bundle/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here                    
/loomio/config/initializers/sidekiq.rb:2: warning: Sidekiq's Delayed Extensions will be removed in Sidekiq 7.0                        
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exis
ts_returns_integer` will be removed in 5.0. You should use `exists?` instead.                                                         
Migrating to AddStancesToThreadForExistingPolls (20221208213445)                                                                      
== 20221208213445 AddStancesToThreadForExistingPolls: migrating ===============                                                       
rake aborted!                                                                                                                         
StandardError: An error has occurred, this and all later migrations canceled:                                                         
                                                                                                                                      
undefined method `created_event' for nil:NilClass                                                                                     
/loomio/app/models/comment.rb:77:in `parent_event'                                                                                    
/loomio/app/models/event.rb:171:in `find_parent_event'                                                                                
/loomio/app/models/event.rb:191:in `max_depth_adjusted_parent'                                                                        
/loomio/app/models/event.rb:110:in `set_parent_and_depth'                                                                             
/loomio/app/models/event.rb:115:in `set_parent_and_depth!'                                                                            
/loomio/app/services/event_service.rb:45:in `each'                                                                                    
/loomio/app/services/event_service.rb:45:in `repair_thread'                                                                           
/loomio/db/migrate/20221208213445_add_stances_to_thread_for_existing_polls.rb:10:in `block in change'                                 
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/delegation.rb:88:in `each'                                     
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/delegation.rb:88:in `each'                                     
/loomio/db/migrate/20221208213445_add_stances_to_thread_for_existing_polls.rb:3:in `change'                                           
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:867:in `exec_migration'                                    
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'                       
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:850:in `block in migrate'                                  
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:849:in `migrate'                                           
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1037:in `migrate'                                          
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'        
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `block in ddl_transaction'                         
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in tra
nsaction'                                                                                                                             
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_
transaction'                                                                                                                          
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in
 synchronize'                                                                                                                         
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'  
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchroniz
e'                                                                                                                                    
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'  
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'       
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transacti
on'                                                                                                                                   
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:209:in `transaction'                                    
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `ddl_transaction'                                  
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'                 
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `each'                                             
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `migrate_without_lock'                             
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `block in migrate'                                 
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1086:in `up'                                        [1/171]
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1061:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
/usr/local/bundle/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:26:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
NoMethodError: undefined method `created_event' for nil:NilClass
/loomio/app/models/comment.rb:77:in `parent_event'
/loomio/app/models/event.rb:171:in `find_parent_event'
/loomio/app/models/event.rb:191:in `max_depth_adjusted_parent'
/loomio/app/models/event.rb:110:in `set_parent_and_depth'
/loomio/app/models/event.rb:115:in `set_parent_and_depth!'
/loomio/app/services/event_service.rb:45:in `each'
/loomio/app/services/event_service.rb:45:in `repair_thread'
/loomio/db/migrate/20221208213445_add_stances_to_thread_for_existing_polls.rb:10:in `block in change'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/delegation.rb:88:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/relation/delegation.rb:88:in `each'
/loomio/db/migrate/20221208213445_add_stances_to_thread_for_existing_polls.rb:3:in `change'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:867:in `exec_migration'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:850:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:849:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1037:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in tra
nsaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_
transaction'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in
 synchronize'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchroniz
e'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transacti
on'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1380:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1251:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1086:in `up'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/migration.rb:1061:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `each'
/usr/local/bundle/gems/activerecord-6.1.7.3/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
/usr/local/bundle/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:26:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
I restarted the with `docker-compose up -d` and now, all threads don't show comments any more anywhere.

I see in the logs some failed SQL requests like this one while trying to create a new thread : 
```
loomio-db      | 2023-04-13 10:32:29.673 UTC [43] ERROR:  column "revoker_id" of relation "discussion_readers" does not exist at character 52
loomio-db      | 2023-04-13 10:32:29.673 UTC [43] STATEMENT:  UPDATE "discussion_readers" SET "revoked_at" = $1, "revoker_id" = $2 WHERE "discussion_readers"."discussion_id" = $3 AND 1=0 AND (revoked_at is not null)
loomio-app     | method=POST path=/api/v1/discussions format=json controller=API::V1::DiscussionsController action=create status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "revoker_id" of relation "discussion_readers" does not exist
loomio-app     | LINE 1: ...PDATE "discussion_readers" SET "revoked_at" = $1, "revoker_i...
loomio-app     |                                                              ^
loomio-app     | ' duration=190.19 view=0.00 db=42.34
loomio-app     |   
loomio-app     | ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "revoker_id" of relation "discussion_readers" does not exist
loomio-app     | LINE 1: ...PDATE "discussion_readers" SET "revoked_at" = $1, "revoker_i...
loomio-app     |                                                              ^
loomio-app     | ):
loomio-app     |   
loomio-app     | app/services/discussion_service.rb:250:in `add_users'
loomio-app     | app/services/discussion_service.rb:24:in `create'
loomio-app     | app/controllers/api/v1/discussions_controller.rb:13:in `create_action'
loomio-app     | app/controllers/api/v1/discussions_controller.rb:7:in `create'
loomio-app     | app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app     | source=rack-timeout id=6c7fa48f-ea37-4e06-9ed2-ac45cf5b7b2a timeout=15000ms service=199ms state=completed
```

Commenting on an existing thread produces this error : 
```
loomio-app     | method=GET path=/api/v1/events format=json controller=API::V1::EventsController action=index status=500 error='NoMethodError: undefined method `parent_type' for #<Comment:0x000055f97f000d88>
loomio-app     | Did you mean?  parent' duration=130.94 view=0.00 db=25.63
loomio-app     | source=rack-timeout id=52fd4423-7a31-4b15-bad6-9562826421fe timeout=15000ms state=ready
loomio-app     |   
loomio-app     | NoMethodError (undefined method `parent_type' for #<Comment:0x000055f97f000d88>
loomio-app     | Did you mean?  parent):
loomio-app     |   
loomio-app     | (eval):11:in `_fast_attributes'
loomio-app     | app/controllers/api/v1/snorlax_base.rb:83:in `respond_with_collection'
loomio-app     | app/controllers/api/v1/snorlax_base.rb:15:in `index'
loomio-app     | app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app     | source=rack-timeout id=3236437b-ea1c-4512-84f2-b7ce45ed408c timeout=15000ms service=135ms state=completed
```

And this also appears quite offen :
```
nginx-proxy_1  | nginx.1     | REDACTED 10.23.11.1 - - [13/Apr/2023:09:34:59 +0000] "GET /api/v1/profile/groups?exclude_types=u
ser HTTP/1.0" 200 6926 "https://REDACTED/d/SEz7bGKH/REDACTED" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/201001
01 Firefox/102.0" "172.18.0.7:3000"                                                                     
loomio-app     | method=GET path=/api/v1/events format=json controller=API::V1::EventsController action=index status=500 error='NoMeth
odError: undefined method `parent_type' for #<Comment:0x00005610bb93d8d0>                               
loomio-app     | Did you mean?  parent' duration=130.09 view=0.00 db=18.90                                           
loomio-app     |                                                                                        
loomio-app     | NoMethodError (undefined method `parent_type' for #<Comment:0x00005610bb93d8d0>                     
loomio-app     | Did you mean?  parent):                                                                             
loomio-app     |                                                                                                     
loomio-app     | (eval):11:in `_fast_attributes'                                                        
loomio-app     | app/controllers/api/v1/snorlax_base.rb:83:in `respond_with_collection'                              
loomio-app     | app/controllers/api/v1/snorlax_base.rb:15:in `index'                                                
loomio-app     | app/helpers/locales_helper.rb:8:in `use_preferred_locale'                                           
loomio-app     | source=rack-timeout id=b752b50e-f9c5-4de8-bb03-398873e3aabd timeout=15000ms service=135ms state=completed
```

I have almost no experience with docker nor rails and I'm not sure how to fix it

**Comment by airblag** [comment]
db:migrate:status shows that this updates are not applied :
```
$ docker-compose run app rake db:migrate:status 
[...] everything up until 
  down    20221208213445  Add stances to thread for existing polls
  down    20230202030032  Make comment parent polymorphic
  down    20230215002323  Groups change new threads max depth
  down    20230217001422  Create received emails
  down    20230309024515  Add revoker id to stances and discussion readers
  down    20230316035618  Change members can invite members to default false
  down    20230316104656  Add created and updated at to poll option
```

**Comment by robguthrie** [comment]
Hi, can you try changing from latest to 'v2.17.1' and run migrations again?

**Comment by robguthrie** [comment]
actually, try v2.15.5

**Comment by airblag** [comment]
Thanks a lot !

I set `LOOMIO_CONTAINER_TAG=v2.15.5` in .env and ran `docker-compose run app rake db:migrate`
My instance seems to work again, but I still have a strange thing happening on one thread (or at least I only found one with this error). It shows buttons for hidden comments which are not existing "16 more" is shown over each comment, and "-1 more" is shown under each comment (see screenshot)

![between_comments](https://user-images.githubusercontent.com/24829620/231761609-2f6ed7b1-c9f9-4b1b-941e-ecff34916141.png)

Maybe some people interacted with our loomio while it was broken. Do you think it's fixable an easy way (otherwise, the thread will be soon deleted so it's not a big matter)?

Should I be able now to switch back to latest and get the rest of the migration ?

**Comment by robguthrie** [comment]
Yes, you can switch back to latest. Thanks for letting me know about this. I'll add a catch to ensure people move through this version during upgrade.
